bf16: true
cutoff_len: 1024
dataset: tx_normal
ddp_timeout: 180000000
do_train: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
gradient_accumulation_steps: 8
learning_rate: 0.0001
logging_steps: 10
lora_target: all
lr_scheduler_type: cosine
model_name_or_path: C:\zk\LLM_Library\Meta-Llama-3.1-8B
num_train_epochs: 3.0
output_dir: C:\zk\txmonitor\LLaMA-Factory\saves\Meta-Llama-3.1-8B\lora\sft_normal
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
save_steps: 100
stage: sft
template: llama3
val_size: 0.1
warmup_ratio: 0.1
